### PR TITLE
fix markup in section 2.1

### PR DESCRIPTION
**Pull request by himorin**
***
<a href="https://pr-preview.s3.amazonaws.com/himorin/string-meta/pull/37.html" title="Last updated on Mar 9, 2020, 4:48 PM UTC (9070da2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/string-meta/37/6715548...himorin:9070da2.html" title="Last updated on Mar 9, 2020, 4:48 PM UTC (9070da2)">Diff</a>

### CODE REVIEW

**Review by xfq — APPROVED** [review]

**Comment by r12a** [comment]
Thanks for proposing this, but actually the markup ought to be `<code class="kw" translate="no">...</code>`

**Comment by xfq** [comment]
What does the `kw` class do? It doesn't seem to be used in `local.css`.

**Comment by r12a** [comment]
See https://w3c.github.io/i18n-activity/guidelines/editing#inline

We should probably add it and several other things to local.css.

**Comment by himorin** [comment]
Updated my edits.
Also, there is around 50 'code' without class="kw", and some of them are attribute name or value, e.g. starting from '@' (incl. one line above in this edit). I suppose we might be better to check and add it to others, once large update finished.

BTW, it seems there is no definition for class="kw" in the section of suggested styling for local.css in the pointed page. Which section should I add to this repository?

**Comment by r12a** [comment]
> Also, there is around 50 'code' without class="kw"

I went through the document and updated those i thought needed it. See the commit log at https://github.com/w3c/string-meta/commit/4b967dcd9d0328b6fe6c1670592b00833ec5463d

**Pull request merged**
