### PR TITLE
Changes to document to create the terminology section, tighten

### PR DESCRIPTION
**Pull request by aphillips**
document structure, and so forth. Prototype for r12a to grok.

### CODE REVIEW

**Comment by aphillips** [comment]
Hi Richard, can you take a look at the PR we discussed in telecon?

**Comment by r12a** [comment]
Been in meetings most of the day.  Trying to get to this. Hopefully tomorrow.

**Comment by r12a** [comment]
The incremental edits you made to the text seem ok.

I'm not really happy with the idea of moving all that text inside a terminology section though.  I don't know about you, but i usually skip the terminology section and just come back to it when i need to understand a term.  I think the reader *needs* to read this section, however, to get the full picture. Much of the information there goes beyond a simple definition. 

That's why i had added the following paragraph, which now appears to be gone:

> It's not possible to consider alternatives to string metadata in a vacuum. Apart from the question of how a consumer will know what base direction to use for a string, the following are things that need to be considered for an end to end process that supports proper application of base direction to strings.

So, to be honest, i don't see any particular benefit to adding this to the terminology section, but i do see a significant downside.

What we could do as a compromise, is leave in place in the terminology section the two short definitions you added for producer and consumer, to address Najib's issue, but reinstate the former section with the rest. How does that sound?

**Comment by aphillips** [comment]
I'm going to merge this PR and then make changes to address your comments Richard.

**Pull request merged**
